sudo: required
services:
  - docker

before_install:
  - docker build -t chitranjan32/docker-react -f Dockerfile.dev .

script:
  - docker run chitranjan32/docker-react npm run test --watchAll=false --coverage
  